on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["8.2", "stable"]
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@v3
      - uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing fmt and its dependencies
        run: raco pkg install --no-docs --auto --name fmt
      - name: Compiling fmt and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps fmt
      - name: Testing fmt
        run: raco test -x -p fmt
